### ISSUE TITLE
cannot find module 

### ISSUE THREAD

**Issue by delirus18** [DarkPower202/Pony.Town#1]
OC:Windows 7 64bit 
Nodejs:12.14.0 
Mongodb:4.2.2 
bug: 
Glup show me error: Cannot find module ./uws_win32_72 
![image](https://user-images.githubusercontent.com/49199033/72177380-5c386480-3402-11ea-878e-85ee9f0ffc0d.png)
![image](https://user-images.githubusercontent.com/49199033/72177529-ae798580-3402-11ea-88ec-92a7e6be0b31.png)

**Comment by LegoDevStudio** [comment]
This is caused by you running an unsupported node version.

The module `clusterws_uws` only supports node v9. You're running v12.

Downgrading to v9 will fix the issue.
